---
name: Send Slack Webhook
description: Send Slack Webhook

inputs:
  slack_webhook:
    description: Slack webhook url
    required: true
  payload_file:
    description: >-
      Slack webhook payload in json format
      see https://app.slack.com/block-kit-builder
      example payload file contents '{"text":"Hello, World!"}'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send webhook
      shell: bash
      id: webhook_result
      env:
        PAYLOAD_FILE: ${{ inputs.payload_file }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
      run: |
        curl -X POST \
          -H 'Content-type: application/json' \
          --data "@${PAYLOAD_FILE} \
          "${SLACK_WEBHOOK}"
