---
name: Send Slack Webhook
description: Send Slack Webhook

inputs:
  slack_webhook:
    description: Slack webhook url
    required: true
  title:
    description: title of slack message
    required: true
  body_file:
    description: Markdown body (plain text file) of slack message
    required: true

runs:
  using: "composite"
  steps:
    - name: Send webhook
      shell: bash
      id: webhook_result
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        TITLE: ${{ inputs.title }}
        BODY_FILE: ${{ inputs.body_file}}
      run: |
        body="$(cat "${BODY_FILE}")"
        ./bin/simple_slack_webhook.py \
          --title "${TITLE}" \
          --body "${body}" \
          --webhook "${SLACK_WEBHOOK}"
