---
name: Demo Scheduled Task
run-name: Demo Scheduled Task

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-scheduled
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    # every day at 16:00 Pacific / 00:00 UTC
    - cron: "0 0 * * *"

permissions:
  contents: read
  actions: read

jobs:
  do_stuff:
    name: Do things and stuff at UTC midnight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v4

      - name: get job id / url
        id: job_id
        uses: ./.github/actions/get_job_id
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Env
        id: set_env
        env:
          PAYLOAD_FILE_PREFIX: /tmp/slack_payload
        # see https://app.slack.com/block-kit-builder
        run: |
          DT="$(date "+%s")"
          body_file="${PAYLOAD_FILE_PREFIX}_${DT}.txt"

          ##############################################
          # body text
          ##############################################
          cat <<EOF | tee "${body_file}"
          This is a \`mrkdwn\` section block
          this is a emoji :ghost:
          *this is bold*,
          and ~this is crossed out~
          EOF
          # ^ if you use backticks, escape them

          ##############################################
          # Save env vars
          ##############################################
          cat <<EOF | tee -a  "$GITHUB_OUTPUT" "$GITHUB_ENV"
          BODY_FILE=${body_file}
          EOF

      - name: Send slack alert
        id: send_slack
        uses: ./.github/actions/send_slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          title: "Hello from the Demo Scheduled Task!"
          body_file: ${{ steps.set_env.outputs.BODY_FILE }}
          job_url: ${{ steps.job_id.outputs.job_url }}
          job_id: ${{ steps.job_id.outputs.job_id }}
